using System;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using YanickSenn.Utils.Events;

namespace YanickSenn.CodeGen.Editor.Events {

    [Generator]
    public class EventGenerator : IGenerator {

        [MenuItem("Tools/Code Generation/Force Generate Events")]
        public static void TriggerGeneration() {
            new EventGenerator().Generate();
        }

        public void Generate() {
            var targetTypes = TypeCache.GetTypesWithAttribute<GenerateEventAttribute>();
            var outputDir = "Assets/Generated/Events";

            if (!Directory.Exists(outputDir)) {
                Directory.CreateDirectory(outputDir);
            }

            foreach (var type in targetTypes) {
                var attr = System.Reflection.CustomAttributeExtensions.GetCustomAttribute<GenerateEventAttribute>(type);
                if (attr != null && attr.Generate) {
                    GenerateEventForType(type, outputDir);
                }
            }

            AssetDatabase.Refresh();
        }

        public void Clear() {
            var outputDir = "Assets/Generated/Events";
            if (Directory.Exists(outputDir)) {
                Directory.Delete(outputDir, true);
                File.Delete(outputDir + ".meta");
            }
            AssetDatabase.Refresh();
        }

        public bool ShouldRetriggerGenerationForAsset(string assetPath) {
            if (string.IsNullOrEmpty(assetPath)) {
                return false;
            }

            return assetPath.EndsWith(".cs", StringComparison.OrdinalIgnoreCase);
        }

        private static void GenerateEventForType(Type type, string outputDir) {
            var className = $"{type.Name}Event";
            var filePath = Path.Combine(outputDir, $"{className}.cs");
            var typeFullName = type.FullName.Replace('+', '.');

            var sb = new StringBuilder();
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using YanickSenn.CodeGen.Attributes;");
            sb.AppendLine("using YanickSenn.Utils.Events;");
            sb.AppendLine();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     This code was generated by YanickSenn.CodeGen.Editor.Events.EventGenerator.");
            sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
            sb.AppendLine("//     the code is regenerated.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("namespace YanickSenn.Generated.Events {");
            sb.AppendLine();
            var menuName = ObjectNames.NicifyVariableName(className);
            sb.AppendLine($"    [Generated]");
            sb.AppendLine($"    [CreateAssetMenu(fileName = \"{className}\", menuName = \"Events/{menuName}\")]");
            sb.AppendLine($"    public class {className} : Event<{typeFullName}> {{ }}");
            sb.AppendLine("}");

            var content = sb.ToString();
            if (!File.Exists(filePath) || File.ReadAllText(filePath) != content) {
                File.WriteAllText(filePath, content);
                Debug.Log($"Generated event: {filePath}");
            }
        }
    }
}
